import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useNoteContext } from '../../context/NoteContext';
import { FaStar, FaThLarge, FaList } from 'react-icons/fa';
const StarredNotes = () => {
    const { notes, starNoteById } = useNoteContext();
    const [viewMode, setViewMode] = useState('grid');
    // Filter for Starred Notes
    // Support both 'isStarred' (backend) and 'starred' (legacy types) just in case
    const starredNotes = notes.filter((note) => note.isStarred || note.starred);
    return (_jsxs("div", { className: "flex flex-col h-full", children: [_jsxs("div", { className: "flex justify-between items-center mb-6", children: [_jsxs("h2", { className: "text-2xl font-bold text-gray-800 dark:text-gray-100 flex items-center gap-2", children: [_jsx(FaStar, { className: "text-yellow-400" }), "Starred Notes"] }), _jsxs("div", { className: "flex bg-gray-200 dark:bg-gray-700 rounded-lg p-1", children: [_jsx("button", { onClick: () => setViewMode('grid'), className: `p-2 rounded-md transition-all ${viewMode === 'grid' ? 'bg-white dark:bg-gray-600 shadow text-purple-600' : 'text-gray-500'}`, children: _jsx(FaThLarge, {}) }), _jsx("button", { onClick: () => setViewMode('list'), className: `p-2 rounded-md transition-all ${viewMode === 'list' ? 'bg-white dark:bg-gray-600 shadow text-purple-600' : 'text-gray-500'}`, children: _jsx(FaList, {}) })] })] }), _jsx("div", { className: "flex-1 overflow-y-auto pr-2 scrollbar-thin", children: starredNotes.length > 0 ? (_jsx("div", { className: viewMode === 'grid' ? 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6' : 'flex flex-col gap-4', children: starredNotes.map((note) => (_jsxs("div", { className: "group bg-white dark:bg-gray-800 p-5 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 hover:shadow-md transition-all relative flex flex-col h-48", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("h4", { className: "text-lg font-bold text-gray-800 dark:text-gray-100 line-clamp-1", children: note.title }), _jsx("button", { onClick: (e) => { e.preventDefault(); starNoteById(note.id || note._id, false); }, className: "text-yellow-400 hover:text-yellow-600", title: "Remove Star", children: _jsx(FaStar, {}) })] }), _jsx("div", { className: "text-gray-600 dark:text-gray-400 text-sm mb-4 line-clamp-3 flex-1", dangerouslySetInnerHTML: { __html: note.content || '' } }), _jsx("div", { className: "mt-auto text-xs text-gray-400", children: new Date(note.updatedAt || note.date).toLocaleDateString() }), _jsx(Link, { to: "/note-editor", state: { note }, className: "absolute inset-0 z-0" })] }, note.id || note._id))) })) : (_jsxs("div", { className: "text-center text-gray-500 mt-20", children: [_jsx(FaStar, { className: "text-6xl text-gray-200 mx-auto mb-4" }), _jsx("p", { className: "text-lg", children: "No starred notes found." }), _jsx("p", { className: "text-sm", children: "Star important notes to see them here." })] })) })] }));
};
export default StarredNotes;
